<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class PenggunaSeeder extends Seeder
{
    /**
     * Seed data dummy pengguna (user & freelancer).
     * Admin tidak termasuk — di-handle oleh AdminSeeder.
     */
    public function run(): void
    {
        $password = Hash::make('123');

        DB::table('pengguna')->insert([
            // --- User biasa ---
            [
                'id_pengguna'    => 3,
                'id_role'        => 2,
                'username'       => 'ahmadfauzi',
                'nama_pengguna'  => 'Ahmad Fauzi',
                'tanggal_lahir'  => '1999-03-12',
                'no_telp'        => '082333333333',
                'email'          => 'ahmad@gmail.com',
                'password'       => $password,
                'id_provinsi'    => 1,
                'id_kabupaten'   => 6,
                'id_kecamatan'   => 15,
                'id_desa'        => 29,
                'alamat_lengkap' => 'Surabaya',
                'foto_profil'    => null,
            ],
            [
                'id_pengguna'    => 7,
                'id_role'        => 2,
                'username'       => 'ferdyansyah',
                'nama_pengguna'  => 'Ferdy Ansyah',
                'tanggal_lahir'  => '1996-06-18',
                'no_telp'        => '082958332745',
                'email'          => 'ferdy@gmail.com',
                'password'       => $password,
                'id_provinsi'    => null,
                'id_kabupaten'   => null,
                'id_kecamatan'   => null,
                'id_desa'        => 29,
                'alamat_lengkap' => 'Mojokerto',
                'foto_profil'    => null,
            ],
            [
                'id_pengguna'    => 8,
                'id_role'        => 2,
                'username'       => 'lindaputri',
                'nama_pengguna'  => 'Linda Putri',
                'tanggal_lahir'  => '2002-02-14',
                'no_telp'        => '082592418334',
                'email'          => 'linda@gmail.com',
                'password'       => $password,
                'id_provinsi'    => null,
                'id_kabupaten'   => null,
                'id_kecamatan'   => null,
                'id_desa'        => 2,
                'alamat_lengkap' => 'Surabaya',
                'foto_profil'    => null,
            ],
            [
                'id_pengguna'    => 9,
                'id_role'        => 2,
                'username'       => 'yogapratama',
                'nama_pengguna'  => 'Yoga Pratama',
                'tanggal_lahir'  => '2001-09-09',
                'no_telp'        => '082129342553',
                'email'          => 'yoga@gmail.com',
                'password'       => $password,
                'id_provinsi'    => null,
                'id_kabupaten'   => null,
                'id_kecamatan'   => null,
                'id_desa'        => 4,
                'alamat_lengkap' => 'Malang',
                'foto_profil'    => null,
            ],
            [
                'id_pengguna'    => 10,
                'id_role'        => 2,
                'username'       => 'bagussetiawan',
                'nama_pengguna'  => 'Bagus Setiawan',
                'tanggal_lahir'  => '1996-12-01',
                'no_telp'        => '08193857235',
                'email'          => 'bagus@gmail.com',
                'password'       => $password,
                'id_provinsi'    => null,
                'id_kabupaten'   => null,
                'id_kecamatan'   => null,
                'id_desa'        => 7,
                'alamat_lengkap' => 'Sidoarjo',
                'foto_profil'    => null,
            ],
            [
                'id_pengguna'    => 11,
                'id_role'        => 2,
                'username'       => 'risky',
                'nama_pengguna'  => 'risky',
                'tanggal_lahir'  => null,
                'no_telp'        => '0881118282345',
                'email'          => 'risky@gmail.com',
                'password'       => $password,
                'id_provinsi'    => null,
                'id_kabupaten'   => null,
                'id_kecamatan'   => null,
                'id_desa'        => null,
                'alamat_lengkap' => null,
                'foto_profil'    => null,
            ],

            // --- Freelancer ---
            [
                'id_pengguna'    => 2,
                'id_role'        => 3,
                'username'       => 'sitinurhaliza',
                'nama_pengguna'  => 'Siti Nurhaliza Wati',
                'tanggal_lahir'  => '2001-07-21',
                'no_telp'        => '08223234595',
                'email'          => 'siti@gmail.com',
                'password'       => $password,
                'id_provinsi'    => 1,
                'id_kabupaten'   => 1,
                'id_kecamatan'   => 1,
                'id_desa'        => 2,
                'alamat_lengkap' => 'Rungkut tengah, Surabaya',
                'foto_profil'    => null,
            ],
            [
                'id_pengguna'    => 4,
                'id_role'        => 3,
                'username'       => 'andiwijaya',
                'nama_pengguna'  => 'Andi Wijaya',
                'tanggal_lahir'  => '1998-03-15',
                'no_telp'        => '08885845116',
                'email'          => 'andi@gmail.com',
                'password'       => $password,
                'id_provinsi'    => 1,
                'id_kabupaten'   => 3,
                'id_kecamatan'   => 8,
                'id_desa'        => 15,
                'alamat_lengkap' => 'Desa Gelam, Kec. Sidoarjo, Kab. Sidoarjo, Jawa Timur',
                'foto_profil'    => null,
            ],
            [
                'id_pengguna'    => 5,
                'id_role'        => 3,
                'username'       => 'rizkypratama',
                'nama_pengguna'  => 'Rizky Pratama',
                'tanggal_lahir'  => '1997-08-09',
                'no_telp'        => '08145449383',
                'email'          => 'rizky@gmail.com',
                'password'       => $password,
                'id_provinsi'    => 1,
                'id_kabupaten'   => 4,
                'id_kecamatan'   => 11,
                'id_desa'        => 21,
                'alamat_lengkap' => 'Driyorejo, Gresik',
                'foto_profil'    => null,
            ],
            [
                'id_pengguna'    => 6,
                'id_role'        => 3,
                'username'       => 'dewirahmawati',
                'nama_pengguna'  => 'Dewi Rahmawati',
                'tanggal_lahir'  => '1995-11-30',
                'no_telp'        => '081259507317',
                'email'          => 'dewi@gmail.com',
                'password'       => $password,
                'id_provinsi'    => 1,
                'id_kabupaten'   => 2,
                'id_kecamatan'   => 6,
                'id_desa'        => 11,
                'alamat_lengkap' => 'Klojen, Malang',
                'foto_profil'    => null,
            ],
            [
                'id_pengguna'    => 12,
                'id_role'        => 3,
                'username'       => 'ririnka',
                'nama_pengguna'  => 'ririnka',
                'tanggal_lahir'  => null,
                'no_telp'        => '083202343294',
                'email'          => 'Ririn@gmail.com',
                'password'       => $password,
                'id_provinsi'    => 1,
                'id_kabupaten'   => 5,
                'id_kecamatan'   => 12,
                'id_desa'        => 23,
                'alamat_lengkap' => 'Mojosari, Mojokerto',
                'foto_profil'    => null,
            ],
        ]);
    }
}
